version: "3"
services:
  shinyproxy:
    build: ./shinyproxy
    restart: on-failure
    networks:
      - shiny-net
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./shinyproxy-logs/server:/log
      - ./shinyproxy-logs/container:/container-logs

networks:
  shiny-net:
    name: shiny-net
