version: "3"
services:
  nginx:
    image: nginx:1.21
    container_name: nginx
    ports:
      - 80:80
      - 443:443
      - 8081:8080
    volumes:
      - ./nginx:/etc/nginx
      - /etc/ssl/imm:/certs:ro
      - ./nginx/public:/public:ro
    depends_on:
      - shinyproxy
      - flower
      - grafana

  shinyproxy:
    image: openanalytics/shinyproxy:2.5.0
    container_name: shinyproxy
    restart: on-failure
    user: root
    ports:
      - 8080:8080
      - 9091:9090
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./shinyproxy/application.yml:/opt/shinyproxy/application.yml:ro
      - ./shinyproxy/templates:/opt/shinyproxy/templates:ro
      - shinyproxy-server:/log
      - shinyproxy-containers:/container-logs

  grafana:
    image: grafana/grafana:8.0.6
    container_name: grafana
    restart: always
    user: root
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:3000/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_AUTH_ANONYMOUS_HIDE_VERSION=true

  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - 6379:6379

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus:ro
      - prometheus-data:/prometheus
    ports:
      - 9090:9090

  celery-ctrap:
    container_name: celery-ctrap
    build: ./celery
    command: celery -A tasks worker -c5 -l info -E -n ctrap
    volumes:
      - ./celery:/celery:ro
      - ../apps/cTRAP/sessions:/data
    depends_on:
      - redis

  flower:
    container_name: flower
    image: mher/flower
    command: celery -A tasks flower --url_prefix=flower --persistent=True --db=/data/flower.db --state_save_interval=1000
    volumes:
      - ./celery:/celery:ro
      - flower-data:/data
    working_dir: /celery
    ports:
      - 5555:5555
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    depends_on:
      - celery-ctrap
      - redis

  rstudio-server:
    container_name: rstudio-server
    build: ./rstudio-server
    ports:
      - 8787:8787
    environment:
      - PASSWORD=hello

  postgres:
    container_name: postgres
    image: postgres:12.8
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  clickhouse:
    container_name: clickhouse
    image: yandex/clickhouse-server:21.7-alpine
    restart: always
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    container_name: plausible
    image: plausible/analytics:latest
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - postgres
      - clickhouse
    ports:
      - 8000:8000
    env_file:
      - ./plausible/plausible-conf.env

networks:
  default:
      name: shiny-net

volumes:
  prometheus-data:
  grafana-data:
  shinyproxy-server:
  shinyproxy-containers:
  postgres-data:
  clickhouse-data:
  flower-data:
