version: "3.9"
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8081:8080
    volumes:
      - ./nginx:/etc/nginx
      - /etc/ssl/imm:/certs:ro
      - ./nginx/public:/public:ro
    depends_on:
      - shinyproxy
      - flower
      - grafana

  shinyproxy:
    image: openanalytics/shinyproxy:2.6.0
    container_name: shinyproxy
    restart: always
    user: root
    ports:
      - 8080:8080
      - 9091:9090
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./shinyproxy/application.yml:/opt/shinyproxy/application.yml:ro
      - ./shinyproxy/templates:/opt/shinyproxy/templates:ro
      - shinyproxy-server:/log
      - shinyproxy-containers:/container-logs

  grafana:
    image: grafana/grafana:8.0.6
    container_name: grafana
    restart: always
    user: root
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:3000/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SECURITY_ADMIN_USER=${GRAPHANA_USER:-graphana}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAPHANA_PASSWORD:-graphana_pass}

  redis:
    image: redis:6-alpine
    container_name: redis
    restart: always
    sysctls:
      - net.core.somaxconn=65535
    ports:
      - 6379:6379

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus:/etc/prometheus:ro
      - prometheus-data:/prometheus
    ports:
      - 9090:9090

  celery-ctrap:
    build: ./celery
    container_name: celery-ctrap
    command: celery -A tasks worker -c5 -l info -E -n ctrap
    restart: always
    volumes:
      - ./celery:/celery:ro
      - ../apps/cTRAP/sessions:/data
    depends_on:
      - redis

  flower:
    image: mher/flower
    container_name: flower
    command: celery -A tasks flower --url_prefix=flower --persistent=True --db=/data/flower.db --state_save_interval=1000
    restart: always
    volumes:
      - ./celery:/celery:ro
      - flower-data:/data
    working_dir: /celery
    ports:
      - 5555:5555
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    depends_on:
      - celery-ctrap
      - redis

  rstudio-server:
    build: ./rstudio-server
    container_name: rstudio-server
    ports:
      - 8787:8787
    environment:
      - PASSWORD=${RSTUDIO_PASSWORD:-rstudio_pass}
    profiles:
      - dev

  postgres:
    image: postgres:12.8
    container_name: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres_pass}
    ports:
      - 5432:5432

  clickhouse:
    image: yandex/clickhouse-server:21.7-alpine
    container_name: clickhouse
    restart: always
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: plausible/analytics:v1
    container_name: plausible
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - postgres
      - clickhouse
    ports:
      - 8000:8000
    environment:
      - ADMIN_USER_EMAIL=${PLAUSIBLE_EMAIL:-someone@email.com}
      - ADMIN_USER_NAME=${PLAUSIBLE_USER:-plausible}
      - ADMIN_USER_PWD=${PLAUSIBLE_PASSWORD:-plausible_pass}
      - BASE_URL=https://compbio.imm.medicina.ulisboa.pt/plausible
      - SECRET_KEY_BASE=RcqevpL5w8SzrSl0lhNy08KDPrtJE8LGXqX/uvozyC6Vap6+yq6w0q10DJICqz06+3PeDopOmQ8Wq6q3kFtaMw==
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/plausible
      - CLICKHOUSE_DATABASE_URL=http://clickhouse:8123/clickhouse

networks:
  default:
      name: shiny-net

volumes:
  prometheus-data:
  grafana-data:
  shinyproxy-server:
  shinyproxy-containers:
  postgres-data:
  clickhouse-data:
  flower-data:
