version: "3"
services:
  # shinyproxy + related services
  shinyproxy:
    container_name: shinyproxy
    build: ./shinyproxy
    restart: on-failure
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./shinyproxy/logs/server:/log
      - ./shinyproxy/logs/container:/container-logs

  grafana:
    image: grafana/grafana:8.0.6
    container_name: grafana
    restart: always
    user: root
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/volume:/vol01/Docker/monitoring
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning

  influxdb:
    image: influxdb:1.8.6
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    volumes:
      - ./influxdb/data:/var/lib/influxdb
      - ./influxdb/volume:/vol01/Docker/monitoring
    environment:
      - INFLUXDB_DB=shinyproxy_usagestats
      - INFLUXDB_USER=shinyproxy_usagestats

  telegraf:
    image: telegraf:1.19.1
    container_name: telegraf
    restart: always
    ports:
      - 8125:8125
    depends_on:
      - "influxdb"
    links:
      - "influxdb"
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
    volumes:
      - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro

  # celery + flower + related services
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - 9090:9090

  celery:
    container_name: celery
    build: ./celery
    command: celery -A tasks worker -l info -E
    volumes:
      - ./celery:/celery
      - ./celery/data:/data
    depends_on:
      - redis

  flower:
    container_name: flower
    image: mher/flower
    command: celery -A tasks flower
    volumes:
      - ./celery:/celery
    working_dir: /celery
    ports:
      - 5555:5555
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    depends_on:
      - celery
      - redis

  rstudio-server:
    container_name: rstudio-server
    build: ./rstudio-server
    ports:
      - 8787:8787
    environment:
      - PASSWORD=hello

  db:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test_db
    ports:
      - "3306:3306"

networks:
  default:
      name: shiny-net
