global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: flower
    metrics_path: '/flower/metrics'
    static_configs:
      - targets: ['flower:5555']
  - job_name: 'shinyproxy'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # ShinyProxy Actuator @ 9090
      - targets: ['shinyproxy:9090'] 
