global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: node-exporter
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: grafana
    static_configs:
      - targets: ['grafana:3000']
  - job_name: nginx-exporter
    static_configs:
      - targets: ['nginx-exporter:9113']
  - job_name: flower
    metrics_path: '/flower/metrics'
    static_configs:
      - targets: ['flower:5555']
  - job_name: 'shinyproxy'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['shinyproxy:9090'] 
