# more info at https://shinyproxy.io/documentation/configuration

spring.application.name: NMorais Lab - Bioinformatic Apps
spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

proxy: 
  title: NMorais Lab - Bioinformatic Apps
  port: 8080
  # bind-address: 127.0.0.1
  hide-navbar: false
  template-path: /opt/shinyproxy/templates
  container-wait-time: 30000
  container-log-path: /container-logs
  usage-stats-url: micrometer

  # app recovery enabled
  stop-proxies-on-shutdown: false
  recover-running-proxies: true

  docker:
    internal-networking: true
    container-network: shiny-net
  specs:
  - id: psichomics
    description: Alternative splicing quantification, visualisation and analysis
    container-image: nunoagostinho/psichomics:1.28.1
    container-cmd: ["R", "-e", "psichomics::psichomics(host='0.0.0.0', port=3838, shinyproxy=TRUE, cache='~/Downloads/AnnotationHub')"]
    container-network: "${proxy.docker.container-network}"
    container-volumes: [ "/srv/apps/psichomics/data:/root/Downloads" ]
    template-properties:
      startup-time: 20s
      listed: true
  - id: voyAGEr
    description: Analysis of age-related gene expression changes in human
    container-image: diseasetranscriptomicslab/voyager:v2.0.2
    container-network: "${proxy.docker.container-network}"
    container-volumes: [ "/srv/apps/voyAGEr/data:/home/app/data" ]
    template-properties:
      listed: true
  - id: cTRAP
    description: Identifying candidate causal perturbations from differential gene expression data
    container-image: nunoagostinho/ctrap:1.14.1
    container-network: "${proxy.docker.container-network}"
    container-cmd: ["R", "-e", "cTRAP::cTRAP(host='0.0.0.0', port=3838, expire=30, flowerURL='http://flower:5555/flower')"]
    container-volumes: [ "/srv/apps/cTRAP/sessions:/data" ]
    template-properties:
      startup-time: 15s
      listed: true
  - id: scStudio_MCT
    container-image: genomeptimm/scstudio_mct:1.6
    container-network: "${proxy.docker.container-network}"
    container-volumes: [ "/srv/apps/scStudio_MCT/datasets:/home/app/datasets" ]
    template-properties:
      listed: true
  - id: scStudio
    container-image: martabica/scstudio-home:1.2
    container-network: "${proxy.docker.container-network}"
    container-volumes: [ "/srv/apps/scStudio/tokens:/home/app/tokens", "/srv/apps/scStudio/public_datasets:/home/app/public_datasets", "/srv/apps/scStudio/session_data:/home/app/session_data" ]
    template-properties:
      listed: true
  - id: scStudio_DATA
    container-image: martabica/scstudio-selectdata:1.1
    container-network: "${proxy.docker.container-network}"
    container-volumes: [ "/srv/apps/scStudio/tokens:/home/app/tokens", "/srv/apps/scStudio/public_datasets:/home/app/public_datasets", "/srv/apps/scStudio/session_data:/home/app/session_data" ]
    template-properties:
      listed: true
  - id: scStudio_QC
    container-image: martabica/scstudio-qc:1.1
    container-network: "${proxy.docker.container-network}"
    container-volumes: [ "/srv/apps/scStudio/tokens:/home/app/tokens", "/srv/apps/scStudio/public_datasets:/home/app/public_datasets", "/srv/apps/scStudio/session_data:/home/app/session_data" ]
    template-properties:
      listed: true
  - id: scStudio_NORM
    container-image: martabica/scstudio-normalization:1.1
    container-network: "${proxy.docker.container-network}"
    container-volumes: [ "/srv/apps/scStudio/tokens:/home/app/tokens", "/srv/apps/scStudio/public_datasets:/home/app/public_datasets", "/srv/apps/scStudio/session_data:/home/app/session_data" ]
    template-properties:
      listed: true
  - id: scStudio_DIMRED
    container-image: martabica/scstudio-dimred:1.1
    container-network: "${proxy.docker.container-network}"
    container-volumes: [ "/srv/apps/scStudio/tokens:/home/app/tokens", "/srv/apps/scStudio/public_datasets:/home/app/public_datasets", "/srv/apps/scStudio/session_data:/home/app/session_data" ]
    template-properties:
      listed: true
  - id: scStudio_CLUSTER
    container-image: martabica/scstudio-clustering:1.1
    container-network: "${proxy.docker.container-network}"
    container-volumes: [ "/srv/apps/scStudio/tokens:/home/app/tokens", "/srv/apps/scStudio/public_datasets:/home/app/public_datasets", "/srv/apps/scStudio/session_data:/home/app/session_data" ]
    template-properties:
      listed: true
  - id: scStudio_DEA
    container-image: martabica/scstudio-dea:1.5
    container-network: "${proxy.docker.container-network}"
    container-volumes: [ "/srv/apps/scStudio/tokens:/home/app/tokens", "/srv/apps/scStudio/public_datasets:/home/app/public_datasets", "/srv/apps/scStudio/session_data:/home/app/session_data" ]
    template-properties:
      listed: true
  - id: scStudio_GSEA
    container-image: martabica/scstudio-fea:1.3
    container-network: "${proxy.docker.container-network}"
    container-volumes: [ "/srv/apps/scStudio/tokens:/home/app/tokens", "/srv/apps/scStudio/public_datasets:/home/app/public_datasets", "/srv/apps/scStudio/session_data:/home/app/session_data" ]
    template-properties:
      listed: true
  - id: scStudio_FEATPLOT
    container-image: martabica/scstudio-featureplots:1.1
    container-network: "${proxy.docker.container-network}"
    container-volumes: [ "/srv/apps/scStudio/tokens:/home/app/tokens", "/srv/apps/scStudio/public_datasets:/home/app/public_datasets", "/srv/apps/scStudio/session_data:/home/app/session_data" ]
    template-properties:
      listed: true
  - id: scStudio_SETTINGS
    container-image: martabica/scstudio-settings:1.1
    container-network: "${proxy.docker.container-network}"
    container-volumes: [ "/srv/apps/scStudio/tokens:/home/app/tokens", "/srv/apps/scStudio/public_datasets:/home/app/public_datasets", "/srv/apps/scStudio/session_data:/home/app/session_data" ]
    template-properties:
      listed: true
  - id: scStudio_REPORT
    container-image: martabica/scstudio-report:1.1
    container-network: "${proxy.docker.container-network}"
    container-volumes: [ "/srv/apps/scStudio/tokens:/home/app/tokens", "/srv/apps/scStudio/public_datasets:/home/app/public_datasets", "/srv/apps/scStudio/session_data:/home/app/session_data" ]
    template-properties:
      listed: true      
  - id: splicingSenescenceDashboard
    display-name: Splicing in senescence
    description: Splicing in senescence (dashboard)
    container-image: marianaferreira/splicing-senescence-dasboard
    container-network: "${proxy.docker.container-network}"
    template-properties:
      startup-time: 20s
      listed: false
  - id: betAS
    description: Intuitive differential alternative splicing analysis
    container-image: marianaferreira/betas:v1.2.1
    container-cmd: ["R", "-e", "betAS::betASapp(host='0.0.0.0', port=3838)"]
    container-network: "${proxy.docker.container-network}"
    template-properties:
      startup-time: 5s
      listed: true

logging:
  file:
    name: /log/shinyproxy.log

management:
  metrics:
    export:
      prometheus:
        enabled: true

server:
  secure-cookies: true
  forward-headers-strategy: native
  frame-options: sameorigin

