proxy:
  title: nmorais
  port: 8080
  hide-navbar: false
  template-path: ./template
  container-log-path: /container-logs
  docker:
    internal-networking: true
    container-network: shiny-net
  specs:
  - id: psichomics
    container-cmd: ["R", "-e", "psichomics::psichomics(host='0.0.0.0', port=3838)"]
    container-image: nunoagostinho/psichomics:1.18.4
    container-network: "${proxy.docker.container-network}"
    #container-volumes: [ "/home/nuno/Downloads:/root/Downloads" ]

logging:
  file:
    /log/shinyproxy.log

server:
  servlet:
    context-path:  /
