proxy:
  title: NMorais Lab - Bioinformatic Apps
  port: 8080
  hide-navbar: false
  template-path: /opt/shinyproxy/templates
  container-wait-time: 30000
  container-log-path: /container-logs
  usage-stats-url: micrometer
  stop-proxies-on-shutdown: false
  recover-running-proxies: true
  docker:
    internal-networking: true
    container-network: shiny-net
  specs:
  - id: psichomics
    description: Alternative splicing quantification, visualisation and analysis
    container-image: nunoagostinho/psichomics:1.20.0
    container-cmd: ["R", "-e", "psichomics::psichomics(host='0.0.0.0', port=3838, shinyproxy=TRUE, cache='~/Downloads/AnnotationHub')"]
    container-network: "${proxy.docker.container-network}"
    container-volumes: [ "/srv/apps/psichomics/data:/root/Downloads" ]
    template-properties:
      startup-time: 20s
  - id: voyAGEr
    description: Analysis of age-related gene expression changes in human
    container-image: arthurschneider/voyager
    container-network: "${proxy.docker.container-network}"
    container-volumes: [ "/srv/apps/voyager/data:/home/app/data" ]
  - id: scStudio_LiMM
    container-image: genomeptimm/scstudio:1.1
    container-network: "${proxy.docker.container-network}"
    container-volumes: [ "/srv/apps/scStudio_LiMM/datasets:/home/app/datasets" ]
  - id: cTRAP
    description: Identifying candidate causal perturbations from differential gene expression data
    container-image: nunoagostinho/ctrap:dev
    container-network: "${proxy.docker.container-network}"
    container-cmd: ["R", "-e", "cTRAP::cTRAP(host='0.0.0.0', port=3838, flowerURL='http://flower:5555/flower')"]
    container-volumes: [ "/srv/apps/cTRAP/sessions:/data" ]
    template-properties:
      startup-time: 15s

logging:
  file:
    /log/shinyproxy.log

management:
  metrics:
    export:
      prometheus:
        enabled: true

server:
  secureCookies: true
  forward-headers-strategy: native
  frameOptions: sameorigin
  servlet:
    context-path:  /
