{
 "title": "ShinyProxy",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Startup Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(startupTime_seconds_sum[1m])) by (spec_id) / sum(rate(startupTime_seconds_count[1m])) by (spec_id)",
     "legendFormat": "{{spec_id}}"
    }
   ]
  },
  {
   "title": "Usage Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(usageTime_seconds_sum[1m])) by (spec_id) / sum(rate(usageTime_seconds_count[1m])) by (spec_id)",
     "legendFormat": "{{spec_id}}"
    }
   ]
  },
  {
   "title": "Users",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "floor(sum(increase(userLogins_total[$__range])) - sum(increase(userLogouts_total[$__range])))",
     "legendFormat": "Users"
    }
   ]
  },
  {
   "title": "Apps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(floor(sum(increase(appStarts_total[$__range])) by (spec_id)) - floor(sum(increase(appStops_total[$__range])) by (spec_id))) != 0",
     "legendFormat": "{{spec_id}}"
    }
   ]
  },
  {
   "title": "Auth failure rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(authFailed_total[20s])) != 0"
    }
   ]
  },
  {
   "title": "Start failure rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(startFailed_total[$__interval])) != 0"
    }
   ]
  }
 ]
}