name: Check Docker Compose

on:
  push

jobs:
  build:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Setup staging mode
        run: ./setup-testing-mode.sh
    
      - name: Test the server
        run: ./test-localhost.sh

      - name: Check running containers
        run: docker ps
