name: Check Docker Compose

on:
  push

jobs:
  build:
    name: Check Docker Compose
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup project
        run: ./setup-testing-mode.sh

      - name: Build Docker Compose stack
        run: docker compose up -d

      - name: Sleep
        run: sleep 10s
        shell: bash
        
      - name: Check running containers
        run: docker ps

      - name: Docker Compose logs
        run: docker compose logs

      - name: Run Cypress unit tests
        uses: cypress-io/github-action@v5
        with:
          install: false
          build: npm i -D cypress
          browser: firefox
        env:
          CYPRESS_VIDEO: false
          ELECTRON_EXTRA_LAUNCH_ARGS: '--disable-gpu'

      - name: Store Cypress screenshots
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: cypress/screenshots
